name: Build and Sync

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: python -m pip install --upgrade setuptools wheel build

    - name: Build wheel
      run: python -m build

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync to remote server
      run: |
        rsync -avz --progress --delete -e "ssh -p 19099" \
          dist/*.whl \
          chenxueliang@ehr.stalent.cn:/home/chenxueliang/lby/emma/dist/